entry_text = ''
players_input = 'Podaj liczbę graczy (max. 3): '
start_game_info = 'Zaczynamy grę! W grze biorą udział:'
field_info = 'Masz pecha. Pora na kolejnego gracza'
no_letter = 'Brak tej litery'
